added control scripts and updated welcome page

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -1,34 +1,38 @@
 #!/bin/bash
 
 source $OPENSHIFT_CARTRIDGE_SDK_BASH
-
-export OPENSHIFT_SPRINGBOOT_VERSION=$(springboot_version)
+SPRINGBOOT_PID_FILE=${OPENSHIFT_HOMEDIR}/app-root/runtime/springboot.pid
 
 function start()
 {
 	if ! is_running; then
 		set +e
-		echo "Starting SpringBoot $OPENSHIFT_SPRINGBOOT_VERSION cartridge"
+		echo "Starting Spring Boot $OPENSHIFT_SPRINGBOOT_VERSION cartridge"
+		pushd $OPENSHIFT_REPO_DIR 1>/dev/null
+		nohup mvn spring-boot:run
+		echo $! > ${SPRINGBOOT_PID_FILE}
+		popd 1>/dev/null
 		set -e
 	else
-		echo "SpringBoot is already running" 1>&2
+		echo "Spring Boot is already running" 1>&2
 	fi
 }
 
 function stop()
 {	
-	if is_running; then
-		set +e
-		echo "Stopping SpringBoot $OPENSHIFT_SPRINGBOOT_VERSION cartridge"
-		set -e
-	else
-		echo "SpringBoot already stopped"
-	fi
+	 if [ -f "$SPRINGBOOT_PID_FILE" ]; then
+      echo "Stopping $cartridge_type cartridge"
+      pid=$(cat $SPRINGBOOT_PID_FILE);
+      echo "Sending SIGTERM to Spring Boot:$pid ..." 1>&2
+      killtree $pid
+    else 
+      echo "Failed to locate Spring Boot PID File" 1>&2
+    fi
 }
 
 function restart()
 {
-	echo "Restarting SpringBoot"
+	echo "Restarting Spring Boot"
 	stop
 	start
 }
@@ -36,9 +40,9 @@ function restart()
 function status()
 {	
 	if is_running; then
-		client_result "SpringBoot is running"
+		client_result "Spring Boot is running"
 	else
-		client_result "SpringBoot is stopped"
+		client_result "Spring Boot is stopped"
 	fi
 	
 	exit 0
@@ -51,11 +55,11 @@ function tidy()
 
 function is_running()
 {
-	if [ -f $OPENSHIFT_SPRINGBOOT_PID ]; then
-		SPRINGBOOT_pid=`cat $OPENSHIFT_SPRINGBOOT_PID 2> /dev/null`
+	if [ -f $SPRINGBOOT_PID_FILE ]; then
+		SPRINGBOOT_pid=`cat $SPRINGBOOT_PID_FILE 2> /dev/null`
 		myid=`id -u`
 
-		if `ps --pid $SPRINGBOOT_pid > /dev/null 2>&1`
+		if `ps --pid $SPRINGBOOT_PID_FILE > /dev/null 2>&1`
 		then 
 			return 0
 		fi
